from ZOV_src.lexicon_src import *

LEXICON_RU: dict[str, str] = LEXICON_SRC_RU
# Словарь кнопок с контактами
LEXICON_LIST_BUTTONS_CONTACTS = LEXICON_SRC_LIST_BUTTONS_CONTACTS

LEXICON_COMMANDS_RU: dict[str, str] = LEXICON_SRC_COMMANDS_RU

LEXICON_COMMANDS_RU_TEST: dict[str, str] = LEXICON_SRC_COMMANDS_RU_TEST

LEXICON_COMMANDS_RU_UPR: dict[str, str] = LEXICON_SRC_COMMANDS_RU_UPR

LEXICON_HI_RU: dict[str, str] = LEXICON_SRC_HI_RU

LEXICON_CONTACTS: dict[str, str] = LEXICON_SRC_CONTACTS

LEXICON_HI_RU_TEST: dict[str, str] = LEXICON_SRC_HI_RU_TEST

LEXICON_HI_RU_UPR: dict[str, str] = LEXICON_SRC_HI_RU_UPR
